# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'updateLocalization.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(645, 823)
        MainWindow.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(100, 20, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 75 oblique 20pt \"Cantarell\";\n"
"color: white")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 290, 521, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_cpf = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_cpf.setMinimumSize(QtCore.QSize(200, 20))
        self.label_cpf.setStyleSheet("font: 14pt \"Cantarell\";\n"
"color: white")
        self.label_cpf.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cpf.setObjectName("label_cpf")
        self.horizontalLayout_3.addWidget(self.label_cpf)
        self.line_edit_cpf = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.line_edit_cpf.setStyleSheet("font: 14pt \"Cantarell\";\n"
"color: white")
        self.line_edit_cpf.setClearButtonEnabled(False)
        self.line_edit_cpf.setObjectName("line_edit_cpf")
        self.horizontalLayout_3.addWidget(self.line_edit_cpf)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_data = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_data.setStyleSheet("font: 14pt \"Cantarell\";\n"
"color: white")
        self.label_data.setAlignment(QtCore.Qt.AlignCenter)
        self.label_data.setObjectName("label_data")
        self.horizontalLayout_2.addWidget(self.label_data)
        self.date_edit = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.date_edit.setAutoFillBackground(False)
        self.date_edit.setStyleSheet("font: 14pt \"Cantarell\";\n"
"color: white")
        self.date_edit.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 1, 11), QtCore.QTime(0, 0, 0)))
        self.date_edit.setMaximumDate(QtCore.QDate(7999, 12, 31))
        self.date_edit.setMinimumDate(QtCore.QDate(2000, 1, 1))
        self.date_edit.setCalendarPopup(True)
        self.date_edit.setCurrentSectionIndex(0)
        self.date_edit.setDate(QtCore.QDate(2018, 1, 11))
        self.date_edit.setObjectName("date_edit")
        self.horizontalLayout_2.addWidget(self.date_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.button_update_event = QtWidgets.QPushButton(self.centralWidget)
        self.button_update_event.setGeometry(QtCore.QRect(380, 540, 131, 51))
        self.button_update_event.setStyleSheet("font: 14pt \"Cantarell\";\n"
"color: white")
        self.button_update_event.setObjectName("button_update_event")
        self.button_menu = QtWidgets.QPushButton(self.centralWidget)
        self.button_menu.setGeometry(QtCore.QRect(80, 540, 161, 51))
        self.button_menu.setStyleSheet("font: 14pt \"Cantarell\";\n"
"color: white")
        self.button_menu.setObjectName("button_menu")
        self.label_event_info = QtWidgets.QLabel(self.centralWidget)
        self.label_event_info.setGeometry(QtCore.QRect(150, 230, 311, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(2)
        self.label_event_info.setFont(font)
        self.label_event_info.setStyleSheet("font: 50 oblique 20 \"Cantarell\";\n"
"color: white")
        self.label_event_info.setAlignment(QtCore.Qt.AlignCenter)
        self.label_event_info.setObjectName("label_event_info")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(150, 80, 311, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(2)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 50 oblique 20 \"Cantarell\";\n"
"color: white")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 130, 363, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_2.setStyleSheet("font: 14pt \"Cantarell\";\n"
"color: white")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.line_edit_cep = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_edit_cep.sizePolicy().hasHeightForWidth())
        self.line_edit_cep.setSizePolicy(sizePolicy)
        self.line_edit_cep.setStyleSheet("font: 14pt \"Cantarell\";\n"
"color: white")
        self.line_edit_cep.setClearButtonEnabled(False)
        self.line_edit_cep.setObjectName("line_edit_cep")
        self.horizontalLayout.addWidget(self.line_edit_cep)
        self.choose_type = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_type.sizePolicy().hasHeightForWidth())
        self.choose_type.setSizePolicy(sizePolicy)
        self.choose_type.setStyleSheet("font: 14pt \"Cantarell\";\n"
"color: white")
        self.choose_type.setObjectName("choose_type")
        self.choose_type.addItem("")
        self.choose_type.addItem("")
        self.choose_type.addItem("")
        self.horizontalLayout.addWidget(self.choose_type)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(360, 130, 251, 81))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.text_price = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.text_price.setMaximumSize(QtCore.QSize(50, 16777215))
        self.text_price.setStyleSheet("font: 14pt \"Cantarell\";\n"
"color: white")
        self.text_price.setObjectName("text_price")
        self.horizontalLayout_4.addWidget(self.text_price)
        self.line_edit_price = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_edit_price.sizePolicy().hasHeightForWidth())
        self.line_edit_price.setSizePolicy(sizePolicy)
        self.line_edit_price.setStyleSheet("font: 14pt \"Cantarell\";\n"
"color: white")
        self.line_edit_price.setClearButtonEnabled(False)
        self.line_edit_price.setObjectName("line_edit_price")
        self.horizontalLayout_4.addWidget(self.line_edit_price)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 645, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>Atualizar chácaras</p></body></html>"))
        self.label_cpf.setText(_translate("MainWindow", "<html><head/><body><p>Organizador-CPF</p></body></html>"))
        self.line_edit_cpf.setInputMask(_translate("MainWindow", "999.999.999.99"))
        self.label_data.setText(_translate("MainWindow", "<html><head/><body><p>Data</p></body></html>"))
        self.date_edit.setDisplayFormat(_translate("MainWindow", "d/M/yy"))
        self.button_update_event.setText(_translate("MainWindow", "Efetuar"))
        self.button_menu.setText(_translate("MainWindow", "Voltar aos serviços"))
        self.label_event_info.setText(_translate("MainWindow", "<html><head/><body><p>Informações da festa:</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p>Atualizações:</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "CEP"))
        self.line_edit_cep.setInputMask(_translate("MainWindow", "99999-999"))
        self.choose_type.setItemText(0, _translate("MainWindow", "Adicionar"))
        self.choose_type.setItemText(1, _translate("MainWindow", "Remover"))
        self.choose_type.setItemText(2, _translate("MainWindow", "Atualizar"))
        self.text_price.setText(_translate("MainWindow", "Preço"))
        self.line_edit_price.setInputMask(_translate("MainWindow", "99999"))
        self.line_edit_price.setText(_translate("MainWindow", "1000"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

